# Generated by Django 5.2.8 on 2025-11-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telegram_chat_id",
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name="Telegram chat id"),
        ),
    ]
