# Generated by Django 5.2.8 on 2025-11-18 09:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("place", models.CharField(blank=True, default="", max_length=255, verbose_name="Место")),
                ("time_of_day", models.TimeField(blank=True, null=True, verbose_name="Время суток")),
                ("action", models.TextField(verbose_name="Действие для привычки")),
                ("is_rewarding", models.BooleanField(default=False, verbose_name="Приятная привычка")),
                (
                    "periodicity_days",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Периодичность выполнения привычки",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True, default="", max_length=255, null=True, verbose_name="Описание вознаграждения"
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(2),
                        ],
                        verbose_name="Время выполнения",
                    ),
                ),
                ("is_public", models.BooleanField(default=False, verbose_name="Публикация привычки в доступ")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False, verbose_name="Время создания записи"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Время обновления записи")),
                (
                    "creator",
                    models.ForeignKey(
                        help_text="Пользователь: создатель привычки",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Привычка",
                    ),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_by",
                        to="habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
                "ordering": ["created_at"],
            },
        ),
    ]
